[pipeline]
input = "picamera"
threshold = "color"
filter = ["contourarea"]
output = "zeromq"

[threshold]
colorl = [50, 100, 70]
coloru = [70, 255, 255]

[filter]
num_tracked_contours = 1

cnt_area_min = 0.0
cnt_area_max = 100.0

percent_filled_min = 90.0
percent_filled_max = 100.0

[output]
team_num = 4308
zmq_ip = "192.168.0.99"

[input]
width = 288
height = 192
fps = 120

[filter.contourarea]
min = 0.0
max = 20.0