[pipeline]
input = "picamera"
threshold = "complexcolor"
filter = ["contourarea", "percentfilled"]
output = "nt"

[tracking]
num_tracked_contours = 1

[threshold]
colorl = [50, 100, 30]
coloru = [70, 255, 255]

[output]
team_num = 4308
ip = "127.0.0.1:1735"

[input]
width = 848
height = 480
fps = 120

[filter.contourarea]
min = 0.0
max = 20.0

[filter.percentfilled]
min = 90.0
max = 100.0