[input]
width = 288
height = 192

[threshold]
colorl = [50, 100, 70]
coloru = [70, 255, 255]

[filter]
num_tracked_contours = 1

cnt_area_min = 0.0
cnt_area_max = 100.0

percent_filled_min = 90.0
percent_filled_max = 100.0

[output]
team_num = 0
zmq_ip = "10.43.8.2"
